// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using RestfulBooker;
//
//    var bookings = Bookings.FromJson(jsonString);

namespace RestSharpClient.Model.RestfulBooker
{
    using Newtonsoft.Json;

    public partial class Auth
    {
        [JsonProperty("token")]
        public string Token { get; set; }
    }
}

