// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using RestfulBooker;
//
//    var bookings = Bookings.FromJson(jsonString);

namespace RestSharpClient.Model.RestfulBooker
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BookingIds
    {
        [JsonProperty("bookingid")]
        public long? Bookingid { get; set; }
    }
}


